### PR TITLE
Fix settings configuration (and Redmine 3.4 compatibility)

### PR DESCRIPTION
**Pull request by klyonrad**
Access the settings hash with strings instead of symbols.

Also adapt the patches to the newer 3.4.x way

### CODE REVIEW

**Comment by davidverdu** [comment]
Thank you for your PR! We need to check if these changes make the plugin still work in version 3.0.x before accepting it. If not, we can create a branch for version 3.0 and keep 3.4 compatibility in master. Let's keep in touch

**Comment by vphantom** [comment]
I see there's been activity last week on this. Are there plans to merge soon?

**Comment by davidverdu** [comment]
PR merged. The issue for Redmine 3.4 is solved. Thank you for your contributions!

**Comment by ashrafalzyoud** [comment]
@klyonrad 
can u update for redmine 5.0

**Comment by klyonrad** [comment]
> can u update for redmine 5.0

@ashrafalzyoud Sorry, this PR is almost 5 years (!) old. I am not really into Redmine plugin development anymore :)

**Comment by ashrafalzyoud** [comment]
@klyonrad  thx for replay
but i think its need small work if any one have work in ruby

**Pull request merged**
